"""Utilities for generating constrained JSON function calls.

This module generates a function call by combining fixed JSON text with
constrained values generated by the language model.

The function name is restricted to the available functions, and each
parameter value is generated according to its type: number, string,
or boolean.

The program controls the JSON structure instead of relying on the model
to generate valid JSON on its own.
"""

from src import FunctionDefinition
from llm_sdk import Small_LLM_Model
from src import (
    get_fullname_func,
    generate_string_value,
    generate_number_value,
    generate_bool_value,
)


def generate_function_call(
    model: Small_LLM_Model,
    ids_list: list[int],
    all_functions: list[FunctionDefinition],
    id_to_token: dict[int, str],
) -> str:
    """Generate a complete function call using constrained decoding.

    The function first generates a valid function name, then finds its
    definition and generates each parameter according to its declared
    type.

    Fixed JSON parts are added directly to the model context, while
    dynamic values are generated with constrained decoding.

    Args:
        model: Language model used for token generation.
        ids_list: Current token IDs of the model context.
        all_functions: Available function definitions.
        id_to_token: Mapping from token IDs to token text.

    Returns:
        The generated function call as a JSON string.

    Raises:
        ValueError: If the generated function name is not found.
    """
    # 1. choisir le nom de fonction
    all_name = [func.name for func in all_functions]
    chosen_name = get_fullname_func(model, ids_list, all_name, id_to_token)

    # 2. trouver la definition complete
    func_def = None
    for func in all_functions:
        if func.name == chosen_name:
            func_def = func
            break
    if func_def is None:
        raise ValueError(f"ERROR: Function {chosen_name} is not found")

    # 3. commencer le JSON et mettre a jour le contexte
    new_ids = model.encode(', "parameters": {')[0].tolist()
    ids_list.extend(new_ids)
    result = f'{{"name": "{chosen_name}", "parameters": {{'

    # 4. generer chaque parametre
    name_params = list(func_def.parameters.keys())
    for i, name in enumerate(name_params):

        # ajouter la cle du parametre au contexte
        new_ids = model.encode(f'"{name}": ')[0].tolist()
        ids_list.extend(new_ids)
        result += f'"{name}": '

        # generer la valeur selon le type
        param_type = func_def.parameters[name].type

        if param_type == "number":
            value = generate_number_value(model, ids_list, id_to_token)
        elif param_type == "string":
            value = generate_string_value(model, ids_list, id_to_token)
        elif param_type == "boolean":
            value = generate_bool_value(model, ids_list, id_to_token)
        else:
            raise ValueError(f"ERROR: Unknown type {param_type}")

        result += value

        # ajouter virgule si pas le dernier parametre
        if i < len(name_params) - 1:
            new_ids = model.encode(", ")[0].tolist()
            ids_list.extend(new_ids)
            result += ", "

    # 5. fermer le JSON
    new_ids = model.encode("}}")[0].tolist()
    ids_list.extend(new_ids)
    result += "}}"

    return result
